# modules/rds/main.tf
#
# The master password is generated by Terraform, never typed by a
# human, and stored in SSM Parameter Store as a SecureString, not in
# any .tf file or tfvars. The backend app will read it from SSM at
# runtime instead of having it baked into an env var in git.

resource "random_password" "master" {
  length  = 24
  special = false # avoid characters that need escaping in connection strings
}

resource "aws_ssm_parameter" "db_password" {
  name  = "/pulseops/${var.name}/db-password"
  type  = "SecureString"
  value = random_password.master.result
  tags  = var.tags
}

resource "aws_db_subnet_group" "this" {
  name       = "${var.name}-db-subnets"
  subnet_ids = var.private_subnet_ids
  tags       = var.tags
}

resource "aws_security_group" "rds" {
  name_prefix = "${var.name}-rds-"
  vpc_id      = var.vpc_id

  ingress {
    description = "Postgres, from inside this VPC only"
    from_port   = 5432
    to_port     = 5432
    protocol    = "tcp"
    cidr_blocks = [var.vpc_cidr_block]
  }

  egress {
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = ["0.0.0.0/0"]
  }

  tags = var.tags
}

resource "aws_db_instance" "this" {
  identifier     = "${var.name}-postgres"
  engine         = "postgres"
  engine_version = "16"
  instance_class = var.instance_class

  allocated_storage     = var.allocated_storage
  storage_encrypted     = true
  db_name               = var.db_name
  username              = var.db_username
  password              = random_password.master.result
  db_subnet_group_name  = aws_db_subnet_group.this.name
  vpc_security_group_ids = [aws_security_group.rds.id]

  multi_az            = false # cost decision for this deployment, documented in root README
  publicly_accessible = false
  backup_retention_period = 1

  # Dev-environment settings: allow clean teardown/rebuild without a
  # manual snapshot step getting in the way.
  skip_final_snapshot = true
  deletion_protection = false

  tags = var.tags
}