# modules/ecs-service/main.tf
#
# Two containers in one task, backend and frontend, exactly matching
# how docker-compose.yml already runs them. Bridge networking with a
# container link lets nginx.conf keep using "http://backend:4000"
# unchanged — no app config needs to know it's running on ECS.
#
# Secrets (DB password, JWT secrets) are never plaintext env vars.
# ECS's own "secrets" mechanism pulls them from SSM at container
# startup and injects them, the app never calls AWS itself.

data "aws_region" "current" {}
data "aws_caller_identity" "current" {}

# --- New secrets this module owns: JWT signing keys ---
# Same pattern as the RDS password: generated by Terraform, never
# typed by a human, stored as SecureString in SSM.

resource "random_password" "jwt_access_secret" {
  length  = 48
  special = false
}

resource "random_password" "jwt_refresh_secret" {
  length  = 48
  special = false
}

resource "aws_ssm_parameter" "jwt_access_secret" {
  name  = "/pulseops/${var.name}/jwt-access-secret"
  type  = "SecureString"
  value = random_password.jwt_access_secret.result
  tags  = var.tags
}

resource "aws_ssm_parameter" "jwt_refresh_secret" {
  name  = "/pulseops/${var.name}/jwt-refresh-secret"
  type  = "SecureString"
  value = random_password.jwt_refresh_secret.result
  tags  = var.tags
}

# --- Where container logs actually go ---

resource "aws_cloudwatch_log_group" "app" {
  name              = "/ecs/${var.name}"
  retention_in_days = 14
  tags              = var.tags
}

# --- Task execution role ---

resource "aws_iam_role" "execution" {
  name = "${var.name}-ecs-execution-role"

  assume_role_policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Effect    = "Allow"
      Principal = { Service = "ecs-tasks.amazonaws.com" }
      Action    = "sts:AssumeRole"
    }]
  })

  tags = var.tags
}

resource "aws_iam_role_policy_attachment" "execution_managed" {
  role       = aws_iam_role.execution.name
  policy_arn = "arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy"
}

resource "aws_iam_role_policy" "execution_ssm" {
  name = "${var.name}-ecs-execution-ssm"
  role = aws_iam_role.execution.id

  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Effect   = "Allow"
      Action   = ["ssm:GetParameters"]
      Resource = "arn:aws:ssm:${data.aws_region.current.name}:${data.aws_caller_identity.current.account_id}:parameter/pulseops/${var.name}/*"
    }]
  })
}

# --- Task role: what the app itself runs as, needed for ECS Exec ---

resource "aws_iam_role" "task" {
  name = "${var.name}-ecs-task-role"

  assume_role_policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Effect    = "Allow"
      Principal = { Service = "ecs-tasks.amazonaws.com" }
      Action    = "sts:AssumeRole"
    }]
  })

  tags = var.tags
}

resource "aws_iam_role_policy" "task_exec" {
  name = "${var.name}-ecs-exec-permissions"
  role = aws_iam_role.task.id

  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Effect = "Allow"
      Action = [
        "ssmmessages:CreateControlChannel",
        "ssmmessages:CreateDataChannel",
        "ssmmessages:OpenControlChannel",
        "ssmmessages:OpenDataChannel"
      ]
      Resource = "*"
    }]
  })
}

# --- The task definition itself ---

resource "aws_ecs_task_definition" "app" {
  family                   = var.name
  requires_compatibilities = ["EC2"]
  network_mode             = "bridge"
  execution_role_arn       = aws_iam_role.execution.arn
  task_role_arn            = aws_iam_role.task.arn

  container_definitions = jsonencode([
    {
      name      = "backend"
      image     = "${var.backend_repository_url}:${var.image_tag}"
      cpu       = 512
      memory    = 512
      essential = true

      portMappings = [
        { containerPort = 4000, hostPort = 0, protocol = "tcp" }
      ]

      environment = [
        { name = "NODE_ENV", value = "production" },
        { name = "PORT", value = "4000" },
        { name = "PGHOST", value = var.db_endpoint },
        { name = "PGPORT", value = "5432" },
        { name = "PGDATABASE", value = var.db_name },
        { name = "PGUSER", value = "pulseops" },
        { name = "PG_POOL_MAX", value = "10" },
        { name = "PGSSLMODE", value = "require" },
        { name = "REDIS_URL", value = "redis://${var.redis_endpoint}:${var.redis_port}" },
        { name = "JWT_ACCESS_TTL", value = "15m" },
        { name = "JWT_REFRESH_TTL", value = "7d" },
        { name = "BCRYPT_ROUNDS", value = "12" },
      ]

      secrets = [
        { name = "PGPASSWORD", valueFrom = var.db_password_parameter_name },
        { name = "JWT_ACCESS_SECRET", valueFrom = aws_ssm_parameter.jwt_access_secret.name },
        { name = "JWT_REFRESH_SECRET", valueFrom = aws_ssm_parameter.jwt_refresh_secret.name },
      ]

      logConfiguration = {
        logDriver = "awslogs"
        options = {
          "awslogs-group"         = aws_cloudwatch_log_group.app.name
          "awslogs-region"        = data.aws_region.current.name
          "awslogs-stream-prefix" = "backend"
        }
      }
    },
    {
      name      = "frontend"
      image     = "${var.frontend_repository_url}:${var.image_tag}"
      cpu       = 256
      memory    = 256
      essential = true
      links     = ["backend"]

      portMappings = [
        { containerPort = 80, hostPort = 80, protocol = "tcp" }
      ]

      logConfiguration = {
        logDriver = "awslogs"
        options = {
          "awslogs-group"         = aws_cloudwatch_log_group.app.name
          "awslogs-region"        = data.aws_region.current.name
          "awslogs-stream-prefix" = "frontend"
        }
      }
    }
  ])

  tags = var.tags
}

resource "aws_ecs_service" "app" {
  name                               = "${var.name}-service"
  cluster                            = var.cluster_name
  task_definition                    = aws_ecs_task_definition.app.arn
  desired_count                      = 1
  enable_execute_command             = true
  deployment_minimum_healthy_percent = 0
  deployment_maximum_percent         = 100

  capacity_provider_strategy {
    capacity_provider = var.capacity_provider_name
    weight             = 1
  }

  # Terraform still creates new task definition revisions when infra
  # settings change (env vars, secrets, CPU/memory), but it no longer
  # forces the SERVICE back to that revision — the CI/CD pipeline owns
  # which revision actually runs, since it deploys on every push.
  # Without this, Terraform and the pipeline fight over the same
  # field, and a routine `terraform apply` can silently roll back a
  # working deploy.
  lifecycle {
    ignore_changes = [task_definition]
  }

  tags = var.tags
}